ex4300_cmds_shell_Q = ["""cprod -A fpc0 -c 'show ppm statistics protocol lacp'""", 
                       """cprod -A fpc0 -c 'show link stats'""", 
                       """cprod -A fpc0 -c 'show ppm adjacencies'""", 
                       """cprod -A fpc0 -c 'show threads cpu'""",
                       """cprod -A fpc0 -c 'show halp-l2 mac_table'""",
                       """cprod -A fpc0 -c 'show halp-pkt pkt-stats'""",
                       """cprod -A fpc0 -c 'show route bridge'""", 
                       """cprod -A fpc0 -c 'show l2 manager bridge-domains detail'""", 
                       """cprod -A fpc0 -c 'show l2 manager mac-table'""", 
                       """cprod -A fpc0 -c 'show l2 manager statistics ipc'""", 
                       """cprod -A fpc0 -c 'show l2 manager statistics ipc-queue'""", 
                       """cprod -A fpc0 -c 'show l2 manager statistics pfe'""", 
                       """cprod -A fpc0 -c 'show l2 manager statistics hal'""", 
                       """cprod -A fpc0 -c 'show l2 manager hw-to-sw-diff'""", 
                       """cprod -A fpc0 -c 'show l2 manager sw-to-hw-diff'""",                        
                       """cprod -A fpc0 -c 'show pfe statistics nhdb'""",
                       """cprod -A fpc0 -c 'show pfe_bcm bcmshell "show errors"'""",
                       """cprod -A fpc0 -c 'show pfe_bcm bcmshell "trunk show"'""",
                       """cprod -A fpc0 -c 'show pfe_bcm bcmshell "pw"'""",
                       """cprod -A fpc0 -c 'show pfe_bcm bcmshell "l2 show"'""", 
                       """cprod -A fpc0 -c 'show pfe_bcm bcmshell "ps"'""",
                       """cprod -A fpc0 -c 'show nhdb all'""",
                       """cprod -A fpc0 -c 'show nhdb summary'""",
                       #"""cprod -A fpc0 -c 'show nhdb type unilist'""",
                       #"""cprod -A fpc0 -c 'show nhdb type unicast'""",
                       """cprod -A fpc0 -c 'show nhdb l2addr stats'""", 
                       """cprod -A fpc0 -c 'show shim bridge interface'""", 
                       """cprod -A fpc0 -c 'show ifd brief'""", 
                       """cprod -A fpc0 -c 'show sfp list'""",
                       """cprod -A fpc0 -c 'show filter'""",
                       """cprod -A fpc0 -c 'show filter hw all'""",
                       """cprod -A fpc0 -c 'show filter hw stats'""",
                       """cprod -A fpc0 -c 'show filter hw groups'""",
                       """cprod -A fpc0 -c 'show filter hw fp_slice'""",
                       """cprod -A fpc0 -c 'show filter counters'""",
                       """cprod -A fpc0 -c 'show ukern_trace handles' | grep " IF " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c 'show ukern_trace handles' | grep NH-HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep RT-HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep TCAM | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep HALP_PKT_ERR | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep PFE-BCM-L2 | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cli -c 'show arp no-resolve | no-more'""", 
                       """cli -c 'show ethernet-switching table | no-more'""", 
                       """cli -c 'show route summary | no-more'""",
                       """cli -c 'show route forwarding-table summary | no-more'""",
                       """cli -c 'show pfe statistics traffic | no-more'""",
                       """cli -c 'show pim interfaces | no-more'""",
                       """cli -c 'show pim neighbors detail | no-more'""",
                       """cli -c 'show pim join extensive| no-more'""",
                       """cli -c 'show pim statistics | no-more'""",
                       """cli -c 'show igmp group detail | no-more'""",
                       """cli -c 'show igmp statistics | no-more'"""]

ex4300_cmds_shell_D = ["vmstat -afimsz",
                       "sysctl -a",
                       "rtinfo -rnV",
                       "ifsmon -dt",    # large output 
                       "ifsmon -p",
                       "ifsmon -kd",
                       "nhinfo -ad",
                       """cprod -A fpc0 -c 'show pfe_bcm bcmshell "l3 l3table show"'""",
                       """cprod -A fpc0 -c 'show nhdb all extensive'""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep "DFW " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep DFW-error | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep DFW-API | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep DFW-detail | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep PFE_BCM_CNTR | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep PFE_BCM_TRUNK | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cprod -A fpc0 -c "show ukern_trace handles" | grep PFE_BCM_COS_HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                       """cli -c 'show route forwarding-table | no-more'""",
                       """cli -c 'show route forwarding-table family inet | no-more'""",
                       """cli -c 'show route forwarding-table family inet6 | no-more'""",
                       """cli -c 'show route forwarding-table multicast extensive | no-more'""",
                       """cli -c 'show multicast route extensive | no-more'""",
                       """cli -c 'show multicast rpf | no-more'""",
                       """cli -c 'show route protocol ospf all extensive | no-more'""",
                       """cli -c 'show route protocol direct all extensive | no-more'""",
                       """cli -c 'show route protocol local all extensive | no-more'""",
                       """cli -c 'show pfe route ip | no-more'""",
                       """cli -c 'show ospf database extensive | no-more'"""]

qfx5100_cmds_shell_Q = ["ifsmon -c",
                        "vmstat -afimsz",
                        "cat /etc/fstab",
                        #"top -S",
                        """cli -c 'show route forwarding-table | no-more'""",   #large output
                        """cprod -A fpc0 -c 'set dc bc "show c"'""",
                        """cprod -A fpc0 -c 'show dcbcm ifd all'""",
                        """cprod -A fpc0 -c 'set dcbcm getconfig'""",
                        """cprod -A fpc0 -c 'show ifd brief'""", 
                        """cprod -A fpc0 -c 'show sfp list'""",
                        #"""cprod -A fpc0 -c 'show sfp 1 '#7:1:96""",
                        #"""cprod -A fpc0 -c 'show sfp 1 info'#7:1:96""",
                        #"""cprod -A fpc0 -c 'show sfp 1 alarms'#7:1:96""",
                        #"""cprod -A fpc0 -c 'show sfp 1 diagnostics all'#7:1:96""",
                        """cprod -A fpc0 -c 'show shim bridge interface'""",
                        """cprod -A fpc0 -c 'show shim trunk statistics'""",
                        """cprod -A fpc0 -c 'show route ccc'""",
                        """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",
                        """cprod -A fpc0 -c 'show pfe statistics nhdb'""",
                        """cprod -A fpc0 -c 'show halp-pkt pkt-stats'""",
                        """cprod -A fpc0 -c 'show link stats'""", 
                        """cprod -A fpc0 -c 'show ppm adjacencies'""",
                        """cprod -A fpc0 -c 'show ppm statistics protocol lacp'""",
                        """cprod -A fpc0 -c 'show threads cpu'""",
                        """cprod -A fpc0 -c 'show shim l2ifl l2circuit'""",
                        """cprod -A fpc0 -c 'show nhdb all'""",
                        """cprod -A fpc0 -c 'show nhdb summary'""",                        
                        """cprod -A fpc0 -c 'show nhdb type unilist'""",
                        """cprod -A fpc0 -c 'show nhdb type unicast'""",
                        """cprod -A fpc0 -c 'show shim route mpls-info'""",
                        """cprod -A fpc0 -c 'show shim route mpls-info statistics'""",
                        """cprod -A fpc0 -c 'show shim route sw-statistics'""",
                        """cprod -A fpc0 -c 'show shim nh sw-statistics'""",
                        """cprod -A fpc0 -c 'show shim nh mpls-tunnel-info'""",
                        """cprod -A fpc0 -c 'show shim nh mpls-tunnel-info summary'""",
                        """cprod -A fpc0 -c 'show shim nh mpls-tunnel-info statistics'""",
                        """cprod -A fpc0 -c 'show ukern_trace handles' | grep MemTracker | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c 'show ukern_trace handles' | grep " IF " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c 'show ukern_trace handles' | grep IFSERVICES | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c 'show ukern_trace handles' | grep IFSTATS | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c 'show ukern_trace handles' | grep NH-HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep COS-HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep "NH " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep "RT " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep RT-HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_L2 | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_TRUNK | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c 'show filter hw all'""",
                        """cprod -A fpc0 -c 'show filter hw groups'""",   
                        """cprod -A fpc0 -c 'show filter hw fp_slice'""",
                        """cprod -A fpc0 -c 'show filter counters'""",
                        """cprod -A fpc0 -c 'show filter hw all non_zero_only 0'""",
                        """cprod -A fpc0 -c 'show filter hw all drop non_zero_only 0'""",
                        """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",                        
                        """cprod -A fpc0 -c 'set dc bc "show c"'""", #repeat #1
                        """cprod -A fpc0 -c 'set dc bc "l2 show"'""",
                        """cprod -A fpc0 -c 'set dc bc "l2 cache show"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg source_vp"'""",  (sched-slip)
                        """cprod -A fpc0 -c 'set dc bc "d chg ing_dvp_table"'""",
                        """cprod -A fpc0 -c 'set dc bc "d chg vlan_xlate"'""",
                        """cprod -A fpc0 -c 'set dc bc "d chg egr_vlan_xlate"'""",
                        """cprod -A fpc0 -c 'set dc bc "ps"'""",
                        """cprod -A fpc0 -c 'set dc bc "vlan show"'""",
                        """cprod -A fpc0 -c 'set dc bc "port xe"'""",
                        """cprod -A fpc0 -c 'set dc bc "phy info"'""",
                        """cprod -A fpc0 -c 'set dc bc "soc"'""",
                        """cprod -A fpc0 -c 'set dc bc "fp show"'""", 
                        """cprod -A fpc0 -c 'set dc bc "l3 multipath show"'""", 
                        """cprod -A fpc0 -c 'set dc bc "l3 defip show"'""",     #large output
                        """cprod -A fpc0 -c 'set dc bc "l3 l3table show"'""",
                        """cprod -A fpc0 -c 'set dc bc "l3 egress show"'""", 
                        """cprod -A fpc0 -c 'set dc bc "l3 intf show"'""", 
                        """cprod -A fpc0 -c 'set dc bc "l3 ip6route show"'""", 
                        """cprod -A fpc0 -c 'set dc bc "l3 ip6host show"'""", 
                        """cprod -A fpc0 -c 'set dc bc "d chg MPLS_ENTRY"'""",
                        """cprod -A fpc0 -c 'set dc bc "d chg EGR_IP_TUNNEL_MPLS"'""", 
                        """cprod -A fpc0 -c 'set dc bc "d chg MPLS_ENTRY"'""", 
                        """cprod -A fpc0 -c 'set dc bc "d chg EGR_L3_INTF"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP"'""",
                        """cprod -A fpc0 -c 'set dc bc "d chg L3_IIF"'""",  #useful?
                        """cprod -A fpc0 -c 'set dc bc "d chg VLAN_MPLS"'""", 
                        """cprod -A fpc0 -c 'set dc bc "d chg MY_STATION_TCAM"'""", 
                        """cprod -A fpc0 -c 'set dc bc "d chg L3_IPMC"'""", 
                        """cprod -A fpc0 -c 'set dc bc "ipmc table show"'""",
                        """cprod -A fpc0 -c 'set dc bc "multicast show"'""",
                        """cprod -A fpc0 -c 'set dc bc "pbmp"'""", 
                        """cprod -A fpc0 -c 'set dc bc "d efp_tcam"'""", 
                        """cprod -A fpc0 -c 'set dc bc "d efp_policy_table 1 2"'""", 
                        """cprod -A fpc0 -c 'set dc bc "list efp_tcam"'""", 
                        """cprod -A fpc0 -c 'set dc bc "list efp_policy"'""", 
                        #"""cprod -A fpc0 -c 'set dc bc "listmem"'""",   #useful? 
                        """cprod -A fpc0 -c 'set dc bc "list re"'""", 
                        """cprod -A fpc0 -c 'set dc bc "list egr_l3_intf"'""",
                        """cprod -A fpc0 -c 'show filter hw all non_zero_only 0'""",    #repeat #2
                        """cprod -A fpc0 -c 'show filter hw all drop non_zero_only 0'""",
                        """cprod -A fpc0 -c 'show filter counters'""", 
                        """cprod -A fpc0 -c 'set dc bc "show c"'""", 
                        """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",
                        """cprod -A fpc0 -c 'show syslog messages'""",
                        """cli -c 'show interface extensive | no-more'""",
                        """cli -c 'show l2circuit connections extensive | no-more'""",
                        """cli -c 'show route summary | no-more'""",
                        """cli -c 'show pfe statistics traffic | no-more'""",
                        """cli -c 'show pim statistics | no-more'""",
                        """cli -c 'show igmp statistics | no-more'""",
                        """cli -c 'show pfe statistics traffic | no-more'""",   #repeat #2
                        """cli -c 'show interface extensive | no-more'""",
                        """cprod -A fpc0 -c 'set dc bc "show c"'""",    #repeat #3
                        """cli -c 'show interfaces diagnostics optics | no-more'""",
                        """cli -c 'show route protocol ospf all extensive | no-more'""",
                        """cli -c 'show route protocol isis all extensive | no-more'""",
                        """cli -c 'show route protocol bgp all extensive | no-more'""", 
                        """cli -c 'show route protocol direct all extensive | no-more'""",
                        """cli -c 'show route protocol local all extensive | no-more'""",
                        """cli -c 'show route forwarding-table summary | no-more'""",
                        """cli -c 'show route forwarding-table family mpls summary | no-more'""",                        
                        """cli -c 'show route forwarding-table family mpls | no-more'""",
                        """cli -c 'show route forwarding-table family inet | no-more'""",   
                        """cli -c 'show route forwarding-table family inet6 | no-more'""",  
                        """cli -c 'show route forwarding-table multicast extensive | no-more'""",
                        """cli -c 'show multicast route extensive | no-more'""",
                        """cli -c 'show multicast rpf | no-more'""",
                        """cli -c 'show ldp session extensive | no-more'""",
                        """cli -c 'show ldp database extensive | no-more'""",
                        """cli -c 'show ospf database extensive | no-more'""",
                        """cli -c 'show igmp group detail | no-more'""",
                        """cli -c 'show pim join summary | no-more'""",                        
                        """cli -c 'show pim interfaces | no-more'""",
                        """cli -c 'show pim neighbors detail | no-more'""",
                        """cli -c 'show pim join extensive | no-more'""",
                        """cprod -A fpc0 -c 'set dc bc "show c"'"""]    #repeat #4

qfx5100_cmds_shell_D = ["rtinfo -rnV",
                        "ifsmon -dt",    # large output 
                        "ifsmon -p",
                        "ifsmon -kd",
                        "nhinfo -ad",
                        """cprod -A fpc0 -c 'set dc bc "show c"'""",
                        """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",                        
                        """cprod -A fpc0 -c 'set dc bc "d chg L3_ENTRY_IPV4_UNICAST"'""",
                        """cprod -A fpc0 -c 'set dc bc "d chg L3_ENTRY_IPV4_MULTICAST"'""",
                        """cprod -A fpc0 -c 'set dc bc "d chg L3_ENTRY_IPV6_UNICAST"'""",
                        """cprod -A fpc0 -c 'set dc bc "d chg L3_ENTRY_IPV6_MULTICAST"'""",
                        """cprod -A fpc0 -c 'set dc bc "d chg EGR_MPLS_VC_AND_SWAP_LABEL_TABLE"'""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_PKT | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep "DFW " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep DFW-error | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep DFW-API | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_API | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_CNTR | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_ERR | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_TCAM | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                        """cprod -A fpc0 -c 'show route ip hw lpm'""",
                        """cprod -A fpc0 -c 'show nhdb all extensive'""",
                        #"""cprod -A fpc0 -c 'show nhdb type unilist extensive'""",
                        #"""cprod -A fpc0 -c 'show nhdb type indirect recursive'""",
                        #"""cprod -A fpc0 -c 'show nhdb type unicast extensive'""",
                        """cprod -A fpc0 -c 'set dc bc "show c"'""", #repeat #2
                        """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",
                        """cli -c 'show pfe route ip table | no-more'""",
                        """cli -c 'show pfe route ip hw host | no-more'""",
                        """cli -c 'show pfe route ip hw lpm | no-more'""",
                        """cli -c 'show pfe route ip hw multicast | no-more'""",
                        """cli -c 'show pfe route inet6 hw host | no-more'""",
                        """cli -c 'show pfe route inet6 hw lpm | no-more'""",
                        """cli -c 'show pfe route inet6 hw multicast | no-more'""",
                        """cprod -A fpc0 -c 'set dc bc "show c"'"""] #repeat #3
                        #"""cprod -A fpc0 -c 'set dc bc "d chg EGR_L3_NEXT_HOP"'""", # CPU hog 
                        #"""cprod -A fpc0 -c 'set dc bc "d chg ING_L3_NEXT_HOP"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP_ONLY"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP_DATA_ONLY"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP_AUX_TABLE"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP_ALPM_IPV4"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP_ALPM_IPV4_1"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP_ALPM_IPV6_64"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP_ALPM_IPV6_64_1"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP_ALPM_IPV6_128"'""",
                        #"""cprod -A fpc0 -c 'set dc bc "d chg L3_DEFIP_PAIR_128"'""",
                        #"""cli -c 'show route all extensive | no-more'""",
                        #"""cli -c 'show route table inet.0 extensive | no-more'""", #redundant?                        


qfx10002_cmds_shell_Q = ["ifsmon -c",
                         "vmstat -afimsz",
                         """cprod -A fpc0 -c 'show nhdb all'""",                         
                         """cprod -A fpc0 -c 'show pepic 0 wanio-info'#7:0:1""",
                         """cprod -A fpc0 -c 'show pepic 0 wanio'#7:0:1""",
                         """cprod -A fpc0 -c 'show pechip 0 igp metadata'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 igp counters'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip notif_stats verbose'""",
                         """cprod -A fpc0 -c 'show pechip trapstats'""",
                         """cprod -A fpc0 -c 'show pechip interrupt'""",
                         """cprod -A fpc0 -c 'show pechip pgq_stats'""",
                         """cprod -A fpc0 -c 'show pechip 0 intr_counts all'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 par_prot_counts all'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 erw pkt_stats'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 edf pkt_stats'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 egp metadata'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 egp counters'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 pgq statistics'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 igp port 0 eth_ruleset'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 egp port 0 gp'#7:0:5""",
                         """cprod -A fpc0 -c 'show pechip 0 igp port 0 eth_params'#7:0:5""",
                         """cprod -A fpc0 -c 'show toe pfe 0 pe 0 toe-inst 0 infra status'#10:0:5""",
                         """cprod -A fpc0 -c 'show toe pfe 0 pe 0 toe-inst 1 infra status'#10:0:5""",
                         """cprod -A fpc0 -c 'show toe pfe 0 pe 0 toe-inst 2 infra status'#10:0:5""",
                         """cprod -A fpc0 -c 'show toe pfe 0 pe 0 toe-inst 3 infra status'#10:0:5""",
                         """cprod -A fpc0 -c 'debug cos halp show active_voqs chip 0'#11:0:5""",
                         """cprod -A fpc0 -c 'show halp-pkt stats 0'#8:0:5""",
                         """cprod -A fpc0 -c 'show halp-pkt agg-cpc-stats'""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " EXPR_L2 " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " EXPR_IF " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " EXPR-DFW-Error " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " EXPR-DFW-API " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " EXPR-DFW-Detail " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " RT-HALP " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " EXPR_PKT_DBG " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " EXPR_PKT_ERR " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " NH-HALP " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " NH-HALP-ERR " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cprod -A fpc0 -c 'show ukern_trace handles' | grep " PEPIC " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                         """cli -c 'show chassis pfchip total detail pfchip-id 0 | no-more'#9:0:1""",
                         """cli -c 'show chassis pfchip total pfchip-id 0 summary | no-more'#8:0:1""",
                         """cli -c 'show chassis pfchip rates detail pfchip-id 0 | no-more'#9:0:1""",
                         """cli -c 'show chassis pfchip rates pfchip-id 0 summary | no-more'#8:0:1""",
                         """cli -c 'show chassis pfchip interrupt-errors pfchip-id 0 | no-more'#8:0:1""",
                         """cli -c 'show chassis pfchip parity-errors pfchip-id 0 | no-more'#8:0:1""",
                         """cli -c 'show chassis pfchip link-errors pfchip-id 0 | no-more'#8:0:1""",
                         """cli -c 'show chassis pfchip vital-errors pfchip-id 0 | no-more'#8:0:1""",
                         """cli -c 'show chassis fan | no-more'""",
                         """cli -c 'show chassis environment pem | no-more'""",
                         """cli -c 'show chassis environment | no-more'""",
                         """cli -c 'show chassis alarms | no-more'""",
                         """cli -c 'show chassis temperature-thresholds | no-more'""",
                         """cli -c 'show interface extensive | no-more'""",
                         """cli -c 'show l2circuit connections extensive | no-more'""",
                         """cli -c 'show pfe statistics traffic | no-more'""",
                         """cli -c 'show pim statistics | no-more'""",
                         """cli -c 'show igmp statistics | no-more'""",
                         """cli -c 'show pfe statistics traffic | no-more'""",   #repeat #2
                         """cli -c 'show interface extensive | no-more'""",
                         """cli -c 'show interfaces diagnostics optics | no-more'""",
                         """cli -c 'show route protocol ospf all extensive | no-more'""",
                         """cli -c 'show route protocol isis all extensive | no-more'""",
                         """cli -c 'show route protocol bgp all extensive | no-more'""", 
                         """cli -c 'show route protocol direct all extensive | no-more'""",
                         """cli -c 'show route protocol local all extensive | no-more'""",
                         """cli -c 'show route forwarding-table | no-more'""",   #large output
                         """cli -c 'show route forwarding-table family mpls | no-more'""",
                         """cli -c 'show route forwarding-table family inet | no-more'""",   
                         """cli -c 'show route forwarding-table family inet6 | no-more'""",  
                         """cli -c 'show route forwarding-table multicast extensive | no-more'""",
                         """cli -c 'show route forwarding-table summary | no-more'""",
                         """cli -c 'show multicast rpf | no-more'""",
                         """cli -c 'show ldp session extensive | no-more'""",
                         """cli -c 'show ldp database extensive | no-more'""",
                         """cli -c 'show ospf database extensive | no-more'""",
                         """cli -c 'show igmp group detail | no-more'""",
                         """cli -c 'show pim join summary | no-more'""",                        
                         """cli -c 'show pim interfaces | no-more'""",
                         """cli -c 'show pim neighbors detail | no-more'""",
                         """cli -c 'show multicast route extensive | no-more'""",
                         """cli -c 'show pim join extensive | no-more'""",
                         """cli -c 'show firewall | no-more'""",
                         """cli -c 'show route summary | no-more'""",
                         """cli -c 'show pfe statistics traffic | no-more'"""]

qfx10002_cmds_shell_D = ["rtinfo -rnV",
                         "ifsmon -dt",    # large output 
                         "ifsmon -p",
                         "ifsmon -kd",
                         "nhinfo -ad",
                         """cli -c 'show pfe route ip table | no-more'""", 
                         """cprod -A fpc0 -c 'show nhdb all extensive'"""]

qfx10008_cmds_shell_Q = ["ifsmon -c",
                         "vmstat -afimsz"
                         """cprod -A fpc0 -c 'show nhdb all'"""]

qfx10008_cmds_shell_D = ["rtinfo -rnV",
                         "ifsmon -dt",    # large output 
                         "ifsmon -p",
                         "ifsmon -kd",
                         "nhinfo -ad",
                         """cli -c 'show pfe route ip table | no-more'""",
                         """cprod -A fpc0 -c 'show nhdb all extensive'"""]


mx_cmds_shell_Q = ["""cli -c 'show chassis routing-engine | no-more'""",
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show system commit | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show bgp summary | no-more'""",
                   """cli -c 'show bgp statistics | no-more'""",
                   """cli -c 'show bgp group | no-more'""",
                   """cli -c 'show bgp neighbor | no-more'""",
                   """cli -c 'show route summary | no-more'""",
                   """cli -c 'show route next-hop database | no-more'""",
                   """cli -c 'show route receive-protocol bgp | no-more'""",
                   """cli -c 'show route advertising-protocol bgp | no-more'""",
                   """cli -c 'show route resolution unresolved | no-more'""",
                   """cli -c 'show route hidden | no-more'""",
                   """cli -c 'show route damping | no-more'""",
                   """cli -c 'show chassis routing-engine | no-more'""",    #repeat #1
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show pfe statistics exceptions | no-more'""",
                   """cli -c 'show ospf overview | no-more'""",
                   """cli -c 'show ospf database summary  | no-more'""",
                   """cli -c 'show ospf database | no-more'""",
                   """cli -c 'show ospf neighbor detail | no-more'""",
                   """cli -c 'show ospf route | no-more'""",
                   """cli -c 'show ospf statistics | no-more'""",
                   """cli -c 'show ospf interface | no-more'""",
                   """cli -c 'show ospf log | no-more'""",
                   """cli -c 'show route protocol ospf | no-more'""",
                   """cli -c 'show isis adjacency extensive | no-more'""",
                   """cli -c 'show mpls interface detail  | no-more'""",
                   """cli -c 'show mpls lsp terse | no-more'""",
                   """cli -c 'show mpls lsp | no-more'""",
                   """cli -c 'show mpls lsp extensive | no-more'""",
                   """cli -c 'show mpls lsp ingress | no-more'""",
                   """cli -c 'show mpls lsp transit | no-more'""",
                   """cli -c 'show ted database | no-more'""",
                   """cli -c 'show chassis routing-engine | no-more'""",    #repeat #2
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show pfe statistics exceptions | no-more'""",
                   """cli -c 'show rsvp interface extensive | no-more'""",
                   """cli -c 'show rsvp neighbor detail | no-more'""",
                   """cli -c 'show rsvp session extensive | no-more'""",
                   """cli -c 'show rsvp session ingress | no-more'""",
                   """cli -c 'show rsvp version | no-more'""",
                   """cli -c 'show route table mpls.0 | no-more'""",
                   """cli -c 'show route table inet.3 | no-more'""",
                   """cli -c 'show chassis hardware | no-more'""",
                   """cli -c 'show chassis fabric summary | no-more'""",
                   """cli -c 'show chassis fabric map | no-more'""",
                   """cli -c 'show chassis fabric fpcs | no-more'""",
                   """cli -c 'show chassis fabric plane | no-more'""",
                   """cli -c 'show chassis fabric destinations | no-more'""",
                   """cli -c 'show chassis fabric reachability | no-more'""",
                   """cli -c 'show chassis routing-engine | no-more'""",    #repeat #3
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show pfe statistics exceptions | no-more'""",
                   """cli -c 'show task memory detail | no-more'""",
                   """cli -c 'show task memory summary | no-more'""",
                   """cli -c 'show task io | no-more'""",
                   """cli -c 'show task replication | no-more'""",
                   """cli -c 'show task history | no-more'""",
                   """cli -c 'show task statistics | no-more'""",
                   """cli -c 'show task job | no-more'""",
                   """cli -c 'show task jobs | no-more'""",
                   """cli -c 'show krt queue | no-more'""",
                   """cli -c 'show krt state | no-more'""",
                   """cli -c 'show interfaces filters | no-more'""",
                   """cli -c 'show firewall detail  | no-more'""",
                   """cli -c 'show firewall log | no-more'""",
                   """cli -c 'show policer detail | no-more'""",
                   """cli -c 'show system connections | no-more'""",
                   """cli -c 'show system statistics | no-more'""",
                   """cli -c 'show chassis routing-engine | no-more'""",    #repeat #4
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show pfe statistics exceptions | no-more'"""]

mx_cmds_shell_D = ["""cli -c 'show chassis routing-engine | no-more'""",    #repeat #5
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show pfe statistics exceptions | no-more'""",
                   """cli -c 'show route table mpls.0 extensive | no-more'""",
                   """cli -c 'show route table inet.3 extensive | no-more'""",
                   #"""cli -c 'show route protocol bgp | no-more'""",
                   #"""cli -c 'show route protocol bgp terse | no-more'""",
                   #"""cli -c 'show route forwarding-table extensive | no-more'""",                  
                   """cli -c 'show route forwarding table family mpls extensive | no-more'""",
                   """cli -c 'show ospf database extensive | no-more'"""]

ptx_cmds_shell_Q =["""cli -c 'show chassis routing-engine | no-more'""",
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show system commit | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show bgp summary | no-more'""",
                   """cli -c 'show bgp statistics | no-more'""",
                   """cli -c 'show bgp group | no-more'""",
                   """cli -c 'show bgp neighbor | no-more'""",
                   """cli -c 'show route summary | no-more'""",
                   #"""cli -c 'show route next-hop database | no-more'""",
                   #"""cli -c 'show route receive-protocol bgp | no-more'""",
                   #"""cli -c 'show route advertising-protocol bgp | no-more'""",
                   """cli -c 'show route resolution unresolved | no-more'""",
                   """cli -c 'show route hidden | no-more'""",
                   #"""cli -c 'show route damping | no-more'""",
                   """cli -c 'show route forwarding-table | no-more'""",
                   """cli -c 'show chassis routing-engine | no-more'""",    #repeat #1
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show ospf overview | no-more'""",
                   """cli -c 'show ospf database summary  | no-more'""",
                   """cli -c 'show ospf database | no-more'""",
                   """cli -c 'show ospf neighbor detail | no-more'""",
                   """cli -c 'show ospf route | no-more'""",
                   """cli -c 'show ospf statistics | no-more'""",
                   """cli -c 'show ospf interface | no-more'""",
                   """cli -c 'show ospf log | no-more'""",
                   """cli -c 'show route protocol ospf | no-more'""",
                   """cli -c 'show isis adjacency extensive | no-more'""",
                   """cli -c 'show mpls interface detail  | no-more'""",
                   """cli -c 'show mpls lsp terse | no-more'""",
                   """cli -c 'show mpls lsp extensive | no-more'""",
                   #"""cli -c 'show mpls lsp ingress | no-more'""",
                   #"""cli -c 'show mpls lsp transit | no-more'""",
                   """cli -c 'show ted database | no-more'""",
                   """cli -c 'show chassis routing-engine | no-more'""",    #repeat #2
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show rsvp interface extensive | no-more'""",
                   """cli -c 'show rsvp neighbor detail | no-more'""",
                   """cli -c 'show rsvp session extensive | no-more'""",
                   #"""cli -c 'show rsvp session ingress | no-more'""",
                   """cli -c 'show rsvp version | no-more'""",
                   """cli -c 'show route table mpls.0 | no-more'""",
                   """cli -c 'show route table inet.3 | no-more'""",
                   """cli -c 'show chassis hardware | no-more'""",
                   """cli -c 'show chassis fabric summary | no-more'""",
                   """cli -c 'show chassis fabric map | no-more'""",
                   """cli -c 'show chassis fabric fpcs | no-more'""",
                   """cli -c 'show chassis fabric plane | no-more'""",
                   """cli -c 'show chassis fabric destinations | no-more'""",
                   """cli -c 'show chassis fabric reachability | no-more'""",
                   """cli -c 'show chassis routing-engine | no-more'""",    #repeat #3
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show task memory detail | no-more'""",
                   """cli -c 'show task memory summary | no-more'""",
                   """cli -c 'show task io | no-more'""",
                   """cli -c 'show task replication | no-more'""",
                   """cli -c 'show task history | no-more'""",
                   """cli -c 'show task statistics | no-more'""",
                   """cli -c 'show task job | no-more'""",
                   """cli -c 'show task jobs | no-more'""",
                   """cli -c 'show krt queue | no-more'""",
                   """cli -c 'show krt state | no-more'""",
                   """cli -c 'show interfaces filters | no-more'""",
                   """cli -c 'show firewall detail  | no-more'""",
                   """cli -c 'show firewall log | no-more'""",
                   """cli -c 'show policer detail | no-more'""",
                   """cli -c 'show system connections | no-more'""",
                   """cli -c 'show system statistics | no-more'""",
                   """cli -c 'show chassis routing-engine | no-more'""",    #repeat #4
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'"""]

ptx_cmds_shell_D =["""cli -c 'show chassis routing-engine | no-more'""",    #repeat #5
                   """cli -c 'show system processes extensive | no-more'""",
                   """cli -c 'show class-of-service fabric statistics | no-more'""",
                   """cli -c 'show pfe statistics traffic | no-more'""",
                   """cli -c 'show pfe statistics notification | no-more'""",
                   """cli -c 'show route table mpls.0 extensive | no-more'""",
                   """cli -c 'show route table inet.3 extensive | no-more'""",
                   #"""cli -c 'show route protocol bgp | no-more'""",
                   #"""cli -c 'show route protocol bgp terse | no-more'""",
                   #"""cli -c 'show route forwarding-table extensive | no-more'""",                  
                   """cli -c 'show route forwarding-table family mpls extensive | no-more'""",
                   """cli -c 'show ospf database extensive | no-more'"""]



srx_cmds_shell_Q = ["sysctl -a",
                    "sysctl vm.kmem_map_free", 
                    "ifsmon -Id", 
                    "ifsmon -c", 
                    "ps -aux",
                    """cli -c 'show chassis cluster statistics'""",
                    """cli -c 'show chassis cluster information'""", 
                    """cli -c 'show chassis cluster information detail'""", 
                    """cli -c 'show config groups'""",
                    """cli -c 'show config chassis cluster'""",
                    """cli -c 'show config interfaces'""",
                    """cli -c 'show chassis hardware'""",
                    """cli -c 'show chassis fpc pic-status'""", 
                    """cli -c 'show chassis cluster status'""",
                    """cli -c 'show chassis cluster interfaces'""",   
                    """cli -c 'show chassis cluster statistics'""", #repeat #2
                    """cli -c 'show chassis cluster information'""", 
                    """cli -c 'show chassis cluster information detail'""", 
                    """cli -c 'request pfe execute command "show services mum" target fwdd'""",
                    """cli -c 'request pfe execute command "show usp nat source-pool statistics" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp nat counter" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp asl stats all" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp jsf jbuf_pool stats" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp jsf counters" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp jsf tcpconfig" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp flow counters all" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp memory segment heap modules" target fwdd'""",
                    """cli -c 'request pfe execute command "show octeon memory" target fwdd'""", 
                    """cli -c 'request pfe execute command "show arena" target fwdd'""", 
                    """cli -c 'request pfe execute command "show dpq stat" target fwdd'""", 
                    """cli -c 'request pfe execute command "show dpq pot" target fwdd'""",
                    """cli -c 'show chassis cluster statistics'""", #repeat #3
                    """cli -c 'show chassis cluster information'""", 
                    """cli -c 'show chassis cluster information detail'""", 
                    """cli -c 'show system virtual-memory | no-more'""",
                    """cli -c 'show security monitoring performance spu | no-more'""", 
                    """cli -c 'show security monitoring performance session | no-more'""",
                    """cli -c 'show system processes extensive | no-more'""", 
                    """cli -c 'show chassis forwarding | no-more'""", 
                    """cli -c 'show system processes memory | no-more'""",  # large output 
                    """cli -c 'show chassis routing-engine | no-more'""", 
                    """cli -c 'show security flow session summary | no-more'""", 
                    """cli -c 'show system alarm | no-more'""",
                    """cli -c 'show chassis cluster statistics'""", #repeat #4
                    """cli -c 'show chassis cluster information'""", 
                    """cli -c 'show chassis cluster information detail'"""]


srx_cmds_shell_D = ["""cli -c 'request pfe execute command "set jsf trace per-plugin-trace disable" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp jsf counters h323-alg" target fwdd'""",    #show usp jsf counters? 
                    """cli -c 'request pfe execute command "show usp jsf counters ras-alg" target fwdd'""",     #show usp jsf counters? 
                    """cli -c 'request pfe execute command "show usp jsf tcpstats" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp jsf plugin-list" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp jsf tcp stats all" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp jsf plugins" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp algs jsf_alg_mgr stats" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp plugins" target fwdd'""",
                    """cli -c 'request pfe execute command "show usp gate statistics" target fwdd'""",
                    """cli -c 'request pfe execute command "show usp nat persistent-nat-table" target fwdd'""", 
                    """cli -c 'request pfe execute command "show usp nat translation-context" target fwdd'""",
                    """cli -c 'show security flow session resource-manager extensive'""",
                    """cli -c 'show security alg h323 counters | no-more'"""]


qfx5100_vxlan_cmds_shell_Q = ["""cprod -A fpc0 -c 'set dc bc "show c"'""",  # repeat #1
                              """cprod -A fpc0 -c 'show halp-pkt pkt-stats'""",
                              """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",                              
                              """cli -c 'show pfe statistics traffic | no-more'""",
                              """cli -c 'show ethernet-switching table | no-more'""",
                              """cli -c 'show ethernet-switching vxlan-tunnel-end-point source | no-more'""",
                              """cli -c 'show ethernet-switching vxlan-tunnel-end-point remote  | no-more'""",
                              """cli -c 'show interfaces vtep | no-more'""",
                              """cli -c 'show ethernet-switching flood extensive | no-more'""",
                              """cli -c 'show route table :vxlan.inet.0 | no-more'""",
                              """cprod -A fpc0 -c 'show ukern_trace 16'""",
                              """cprod -A fpc0 -c 'show shim virtual vport'""",
                              """cprod -A fpc0 -c 'show shim virtual vtep'""",
                              """cprod -A fpc0 -c 'show shim virtual error-counters'""",
                              """cprod -A fpc0 -c 'show shim virtual bridge-domain'""",
                              """cprod -A fpc0 -c 'show shim virtual network_ifd_to_egress_mapping'""",
                              """cprod -A fpc0 -c 'show l2 manager vnid'""",
                              """cprod -A fpc0 -c 'show l2 manager bridge-domains'""",
                              """cprod -A fpc0 -c 'set dc bc "d chg ipmc"'""",
                              "ifsmon -c",
                              "vmstat -afimsz",
                              """cli -c 'show route forwarding-table | no-more'""",   #large output
                              """cprod -A fpc0 -c 'show dcbcm ifd all'""",
                              """cprod -A fpc0 -c 'set dcbcm getconfig'""",
                              """cprod -A fpc0 -c 'show ifd brief'""", 
                              """cprod -A fpc0 -c 'show sfp list'""",
                              """cprod -A fpc0 -c 'show filter hw all'""",
                              """cprod -A fpc0 -c 'show filter hw groups'""",   
                              """cprod -A fpc0 -c 'show filter hw fp_slice'""",
                              """cprod -A fpc0 -c 'show filter counters'""",
                              """cprod -A fpc0 -c 'show filter hw all non_zero_only 0'""",
                              """cprod -A fpc0 -c 'show filter hw all drop non_zero_only 0'""",
                              """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",                              
                              """cprod -A fpc0 -c 'show ukern_trace handles' | grep MemTracker | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c 'show ukern_trace handles' | grep " IF " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c 'show ukern_trace handles' | grep IFSERVICES | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c 'show ukern_trace handles' | grep IFSTATS | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c 'show ukern_trace handles' | grep NH-HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep COS-HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep "NH " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep "RT " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep RT-HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_L2 | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_TRUNK | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c 'set dc bc "show c"'""",  #repeat #2
                              """cprod -A fpc0 -c 'show halp-pkt pkt-stats'""",
                              """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",                              
                              """cli -c 'show pfe statistics traffic | no-more'""",                              
                              """cprod -A fpc0 -c 'show link stats'""", 
                              """cprod -A fpc0 -c 'show ppm adjacencies'""",
                              """cprod -A fpc0 -c 'show ppm statistics protocol lacp'""",
                              """cprod -A fpc0 -c 'show threads cpu'""",
                              """cprod -A fpc0 -c 'show nhdb all'""",
                              """cprod -A fpc0 -c 'show nhdb summary'""",                        
                              """cprod -A fpc0 -c 'show nhdb type unilist'""",
                              """cprod -A fpc0 -c 'show nhdb type unicast'""",
                              """cprod -A fpc0 -c 'set dc bc "l2 show"'""",
                              """cprod -A fpc0 -c 'set dc bc "l2 cache show"'""",
                              """cprod -A fpc0 -c 'set dc bc "d chg ing_dvp_table"'""",
                              """cprod -A fpc0 -c 'set dc bc "d chg vlan_xlate"'""",
                              """cprod -A fpc0 -c 'set dc bc "d chg egr_vlan_xlate"'""",
                              """cprod -A fpc0 -c 'set dc bc "ps"'""",
                              """cprod -A fpc0 -c 'set dc bc "vlan show"'""",
                              """cprod -A fpc0 -c 'set dc bc "port xe"'""",
                              """cprod -A fpc0 -c 'set dc bc "phy info"'""",
                              """cprod -A fpc0 -c 'set dc bc "soc"'""",
                              """cprod -A fpc0 -c 'set dc bc "fp show"'""", 
                              """cprod -A fpc0 -c 'set dc bc "l3 multipath show"'""", 
                              """cprod -A fpc0 -c 'set dc bc "l3 defip show"'""",     #large output
                              """cprod -A fpc0 -c 'set dc bc "l3 l3table show"'""",
                              """cprod -A fpc0 -c 'set dc bc "l3 egress show"'""", 
                              """cprod -A fpc0 -c 'set dc bc "l3 intf show"'""", 
                              """cprod -A fpc0 -c 'set dc bc "l3 ip6route show"'""", 
                              """cprod -A fpc0 -c 'set dc bc "l3 ip6host show"'""", 
                              """cprod -A fpc0 -c 'set dc bc "d chg EGR_L3_INTF"'""",
                              """cprod -A fpc0 -c 'set dc bc "d chg MY_STATION_TCAM"'""", 
                              """cprod -A fpc0 -c 'set dc bc "d chg L3_IPMC"'""", 
                              """cprod -A fpc0 -c 'set dc bc "ipmc table show"'""",
                              """cprod -A fpc0 -c 'set dc bc "multicast show"'""",
                              """cprod -A fpc0 -c 'set dc bc "pbmp"'""", 
                              """cprod -A fpc0 -c 'set dc bc "d efp_tcam"'""", 
                              """cprod -A fpc0 -c 'set dc bc "d efp_policy_table 1 2"'""", 
                              """cprod -A fpc0 -c 'set dc bc "list efp_tcam"'""", 
                              """cprod -A fpc0 -c 'set dc bc "list efp_policy"'""", 
                              """cprod -A fpc0 -c 'set dc bc "list re"'""", 
                              """cprod -A fpc0 -c 'set dc bc "list egr_l3_intf"'""",
                              """cprod -A fpc0 -c 'show filter hw all non_zero_only 0'""",    #repeat #2
                              """cprod -A fpc0 -c 'show filter hw all drop non_zero_only 0'""",
                              """cprod -A fpc0 -c 'show filter counters'""", 
                              """cprod -A fpc0 -c 'set dc bc "show c"'""",  #repeat #3 
                              """cprod -A fpc0 -c 'show halp-pkt pkt-stats'""",
                              """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",                              
                              """cli -c 'show pfe statistics traffic | no-more'""",  
                              """cprod -A fpc0 -c 'show syslog messages'""",
                              """cli -c 'show interface extensive | no-more'""",
                              """cli -c 'show route summary | no-more'""",
                              """cli -c 'show route forwarding-table summary | no-more'""",
                              """cli -c 'show pim statistics | no-more'""",
                              """cli -c 'show igmp statistics | no-more'""",
                              """cli -c 'show interface extensive | no-more'""",
                              """cprod -A fpc0 -c 'set dc bc "show c"'""",    #repeat #4
                              """cprod -A fpc0 -c 'show halp-pkt pkt-stats'""",
                              """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",                              
                              """cli -c 'show pfe statistics traffic | no-more'""",
                              """cli -c 'show interfaces diagnostics optics | no-more'""",
                              """cli -c 'show route protocol ospf all extensive | no-more'""",
                              """cli -c 'show route protocol isis all extensive | no-more'""",
                              """cli -c 'show route protocol bgp all extensive | no-more'""", 
                              """cli -c 'show route protocol direct all extensive | no-more'""",
                              """cli -c 'show route protocol local all extensive | no-more'""",
                              """cli -c 'show route forwarding-table family inet | no-more'""",   
                              """cli -c 'show route forwarding-table family inet6 | no-more'""",  
                              """cli -c 'show route forwarding-table multicast extensive | no-more'""",
                              """cli -c 'show multicast route extensive | no-more'""",
                              """cli -c 'show multicast rpf | no-more'""",
                              """cli -c 'show ospf database extensive | no-more'""",
                              """cli -c 'show igmp group detail | no-more'""",
                              """cli -c 'show pim join summary | no-more'""",                        
                              """cli -c 'show pim interfaces | no-more'""",
                              """cli -c 'show pim neighbors detail | no-more'""",
                              """cli -c 'show pim join extensive | no-more'""",
                              """cprod -A fpc0 -c 'set dc bc "show c"'"""]    #bogus
 
qfx5100_vxlan_cmds_shell_D = ["rtinfo -rnV",
                              "ifsmon -dt",    # large output 
                              "ifsmon -p",
                              "ifsmon -kd",
                              "nhinfo -ad",
                              """cprod -A fpc0 -c 'set dc bc "show c"'""",    #repeat #5
                              """cprod -A fpc0 -c 'show halp-pkt pkt-stats'""",
                              """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",                              
                              """cli -c 'show pfe statistics traffic | no-more'""",
                              #"""cprod -A fpc0 -c 'set dc bc "d chg L3_ENTRY_IPV4_UNICAST"'""",
                              #"""cprod -A fpc0 -c 'set dc bc "d chg L3_ENTRY_IPV4_MULTICAST"'""",
                              #"""cprod -A fpc0 -c 'set dc bc "d chg L3_ENTRY_IPV6_UNICAST"'""",
                              #"""cprod -A fpc0 -c 'set dc bc "d chg L3_ENTRY_IPV6_MULTICAST"'""",
                              """cprod -A fpc0 -c 'set dc bc "d chg EGR_MPLS_VC_AND_SWAP_LABEL_TABLE"'""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_PKT | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep "DFW " | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep DFW-error | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep DFW-API | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_HALP | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_API | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_CNTR | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_ERR | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c "show ukern_trace handles" | grep BRCM_DFW_TCAM | awk '{print "\\"show ukern_trace",$1,"\\""}' | xargs cprod -A fpc0 -c""",
                              """cprod -A fpc0 -c 'show route ip hw lpm'""",
                              """cprod -A fpc0 -c 'show nhdb all extensive'""",
                              """cprod -A fpc0 -c 'set dc bc "show c"'""",    #repeat #6
                              """cprod -A fpc0 -c 'show halp-pkt pkt-stats'""",
                              """cprod -A fpc0 -c 'show hw forwarding-drop-cnt'""",                              
                              """cli -c 'show pfe statistics traffic | no-more'""",
                              """cli -c 'show pfe route ip table | no-more'""",
                              """cli -c 'show pfe route ip hw host | no-more'""",
                              """cli -c 'show pfe route ip hw lpm | no-more'""",
                              """cli -c 'show pfe route ip hw multicast | no-more'""",
                              """cli -c 'show pfe route inet6 hw host | no-more'""",
                              """cli -c 'show pfe route inet6 hw lpm | no-more'"""]

